<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="8231" started-at="2022-02-08T12:35:20 CET" finished-at="2022-02-08T12:35:28 CET">
    <groups>
    </groups>
    <test name="Default test" duration-ms="8231" started-at="2022-02-08T12:35:20 CET" finished-at="2022-02-08T12:35:28 CET">
      <class name="d07_02_2022_tests.FormTest">
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:d07_02_2022_tests.FormTest@63440df3]" name="beforeMethod" is-config="true" duration-ms="3598" started-at="2022-02-08T12:35:20 CET" finished-at="2022-02-08T12:35:23 CET">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="formTest()[pri:0, instance:d07_02_2022_tests.FormTest@63440df3]" name="formTest" duration-ms="478" started-at="2022-02-08T12:35:23 CET" finished-at="2022-02-08T12:35:24 CET">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Data is not saved. expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Data is not saved. expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at d07_02_2022_tests.FormTest.formTest(FormTest.java:47)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- formTest -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:d07_02_2022_tests.FormTest@63440df3]" name="afterMethod" is-config="true" duration-ms="4122" started-at="2022-02-08T12:35:24 CET" finished-at="2022-02-08T12:35:28 CET">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- d07_02_2022_tests.FormTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
